// <auto-generated />
using System;
using GP.API.Tower.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GP.API.Tower.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630074408_CreateShip")]
    partial class CreateShip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GP.API.Tower.Model.Ship", b =>
                {
                    b.Property<string>("MMSI")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MMSI")
                        .HasComment("MMSI");

                    b.Property<DateTimeOffset?>("BuildingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Draught")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MMSI");

                    b.ToTable("Ship", t =>
                        {
                            t.HasComment("Ship");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
