// <auto-generated />
using System;
using GP.API.Tower.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GP.API.Tower.Migrations
{
    [DbContext(typeof(TowerDbContext))]
    partial class TowerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GP.API.Model.Ship", b =>
                {
                    b.Property<string>("MMSI")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MMSI")
                        .HasComment("MMSI");

                    b.Property<DateTimeOffset?>("BuildingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Draught")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("ModificationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MMSI");

                    b.ToTable("Ship", t =>
                        {
                            t.HasComment("Ship");
                        });
                });

            modelBuilder.Entity("GP.API.Model.ShipPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Heading")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("MMSI")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Speed")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("MMSI");

                    b.ToTable("ShipPosition", t =>
                        {
                            t.HasComment("Ship");
                        });
                });

            modelBuilder.Entity("GP.API.Model.ShipPosition", b =>
                {
                    b.HasOne("GP.API.Model.Ship", "Ship")
                        .WithMany("ShipPositions")
                        .HasForeignKey("MMSI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("GP.API.Model.Ship", b =>
                {
                    b.Navigation("ShipPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
